name: one_chat
description: "One Chat - Realtime Messaging App built with Flutter and Firebase"
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  firebase_core: ^2.27.0
  firebase_auth: ^4.17.8
  firebase_database: ^10.4.9
  firebase_storage: ^11.6.9
  image_picker: ^1.0.7
  intl: ^0.19.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
